# Generated by Django 4.2.6 on 2024-01-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='desc',
            new_name='descp',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='name',
            new_name='names',
        ),
    ]
